# Generated by Django 4.1.1 on 2022-09-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_person_updatedper_alter_person_cinper_and_more'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activiteFK', to='interaction.activite'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='dateDebutAbo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='dateFinAbo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membreFK', to='account.membre'),
        ),
    ]
