# Generated by Django 4.1.1 on 2022-09-14 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPer', models.CharField(max_length=50)),
                ('prenomPer', models.CharField(max_length=50)),
                ('adressPer', models.CharField(blank=True, max_length=150)),
                ('numeroTelPer', models.IntegerField(blank=True, null=True)),
                ('cinPer', models.IntegerField(blank=True, null=True)),
                ('dateAdhesion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.person')),
            ],
            bases=('account.person', models.Model),
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.person')),
                ('metierMem', models.CharField(blank=True, max_length=50)),
            ],
            bases=('account.person', models.Model),
        ),
    ]
