# Generated by Django 4.1.1 on 2022-09-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_person_cinper_alter_person_numerotelper'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updatedPer',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cinPer',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nomPer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='prenomPer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
